Repository u413-284-si/webserv, pull requests merged in 2024-12, with the labels that each got.

#94 30 add default location when creating a server
  config_files/directive_inheritance.conf
  config_files/listen_localhost_and_port.conf
  config_files/listen_only_localhost.conf
  config_files/location_path.conf
  inc/ConfigFileParser.hpp
  src/ConfigFile.cpp
  src/ConfigFileParser.cpp
  src/LogOstreamInserters.cpp
  src/main.cpp
  src/utilities.cpp
  test/test_ConfigFileParser.cpp
  test/test_OstreamInserters.cpp
Labels: enhancement

#95 81 implement method post
  Makefile
  inc/AutoindexHandler.hpp
  inc/FileSystemPolicy.hpp
  inc/FileWriteHandler.hpp
  inc/MockFileSystemPolicy.hpp
  inc/ResponseBodyHandler.hpp
  inc/StatusCode.hpp
  src/AutoindexHandler.cpp
  src/ConfigFile.cpp
  src/FileSystemPolicy.cpp
  src/FileWriteHandler.cpp
  src/LogOstreamInserters.cpp
  src/RequestParser.cpp
  src/ResponseBodyHandler.cpp
  src/ResponseBuilder.cpp
  src/Server.cpp
  src/utilities.cpp
  test/testRequests/reqPost
  test/test_FileWriteHandler.cpp
Labels: enhancement

#110 107 set up integration end2end testing
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .gitignore
  Makefile
  html/directory/subdirectory/placeholder
  html/uploads/placeholder
  inc/Log.hpp
  src/EpollWrapper.cpp
  test/integration/conftest.py
  test/integration/pytest.ini
  test/integration/server_management/__init__.py
  test/integration/server_management/test_signal.py
  test/integration/server_response/__init__.py
  test/integration/server_response/conftest.py
  test/integration/server_response/test_CGI.py
  test/integration/server_response/test_GET.py
  test/integration/server_response/test_POST.py
  test/integration/server_response/test_invalid.py
  test/unit/test_AutoindexHandler.cpp
  test/unit/test_CGIHandler.cpp
  test/unit/test_ConfigFileParser.cpp
  test/unit/test_FileWriteHandler.cpp
  test/unit/test_OstreamInserters.cpp
  test/unit/test_ResponseBodyHandler.cpp
  test/unit/test_SocketPolicy_retrieveSocketInfo.cpp
  test/unit/test_TargetResourceHandler.cpp
  test/unit/test_acceptConnections.cpp
  test/unit/test_checkForTimeout.cpp
  test/unit/test_connectionReceiveFromCGI.cpp
  test/unit/test_connectionReceiveHeader.cpp
  test/unit/test_connectionSendResponse.cpp
  test/unit/test_connectionSendToCGI.cpp
  test/unit/test_createVirtualServer.cpp
  test/unit/test_handleCompleteRequestHeader.cpp
  test/unit/test_initVirtualServers.cpp
  test/unit/test_isDuplicateServer.cpp
  test/unit/test_parseBody.cpp
  test/unit/test_parseHeader_Headers.cpp
  test/unit/test_parseHeader_RequestLine.cpp
  test/unit/test_registerCGIFileDescriptor.cpp
  test/unit/test_registerConnection.cpp
  test/unit/test_registerVirtualServer.cpp
  test/unit/test_selectServerConfig.cpp
  test/unit/test_shutdownServer.cpp
  test/unit/test_utils.cpp
Labels: enhancement

#102 97 targetresourcehandler throw if no default location
  src/LogOstreamInserters.cpp
  src/ResponseBodyHandler.cpp
  src/TargetResourceHandler.cpp
  src/utilities.cpp
  test/unit/test_TargetResourceHandler.cpp
Labels: bug

#105 69 use default config file if no file provided at prog call
  src/main.cpp
Labels: enhancement

#108 104 request body not processed when read into connectionm buffer together with request headers
  cgi-bin/time.py
  html/index.html
  html/submit.html
  inc/Server.hpp
  src/Server.cpp
  test/testRequests/reqCGIPostChunked
  test/testRequests/reqCgiGet
  test/testRequests/reqCgiGetTime
  test/testRequests/reqCgiGetUploaded
  test/testRequests/reqCgiPost
  test/testRequests/reqCgiUpload
  test/testRequests/reqPost
  test/testRequests/reqWithBody
  test/unit/test_handleCompleteRequestHeader.cpp
Labels: bug

#101 82 allow redirection
  Makefile
  inc/ConfigFile.hpp
  inc/HTTPRequest.hpp
  inc/StatusCode.hpp
  inc/TargetResourceHandler.hpp
  inc/utilities.hpp
  src/ConfigFile.cpp
  src/HTTPRequest.cpp
  src/LogOstreamInserters.cpp
  src/ResponseBodyHandler.cpp
  src/Server.cpp
  src/TargetResourceHandler.cpp
  src/utilities.cpp
  test/unit/test_OstreamInserters.cpp
  test/unit/test_ResponseBodyHandler.cpp
  test/unit/test_TargetResourceHandler.cpp
  test/unit/test_helpers.cpp
Labels: enhancement

#116 106 implement maxbodysize
  Makefile
  inc/ConfigFile.hpp
  inc/Method.hpp
  inc/Server.hpp
  inc/constants.hpp
  src/ConfigFile.cpp
  src/LogOstreamInserters.cpp
  src/Server.cpp
  src/TargetResourceHandler.cpp
  src/constants.cpp
  test/integration/server_response/test_POST.py
  test/unit/test_OstreamInserters.cpp
  test/unit/test_TargetResourceHandler.cpp
  test/unit/test_connectionReceiveBody.cpp
Labels: bug, enhancement

#118 115 percent encoding normalisation
  html/images/grüne äpfel.jpg
  inc/RequestParser.hpp
  inc/error.hpp
  src/RequestParser.cpp
  test/integration/server_response/test_GET.py
  test/integration/server_response/test_invalid.py
  test/unit/test_parseHeader_RequestLine.cpp
Labels: enhancement

#103 96 implement directive alias
  html/index.html
  inc/ConfigFile.hpp
  inc/utilities.hpp
  src/ConfigFile.cpp
  src/TargetResourceHandler.cpp
  src/utilities.cpp
  test/integration/server_response/test_GET.py
  test/unit/test_TargetResourceHandler.cpp
  test/unit/test_utils.cpp
Labels: enhancement

#113 112 file with no permission should return 403
  inc/FileSystemPolicy.hpp
  inc/HTTPRequest.hpp
  inc/TargetResourceHandler.hpp
  src/FileSystemPolicy.cpp
  src/FileWriteHandler.cpp
  src/HTTPRequest.cpp
  src/LogOstreamInserters.cpp
  src/ResponseBodyHandler.cpp
  src/Server.cpp
  src/TargetResourceHandler.cpp
  test/integration/server_response/test_error.py
  test/unit/test_OstreamInserters.cpp
  test/unit/test_ResponseBodyHandler.cpp
  test/unit/test_TargetResourceHandler.cpp
Labels: bug

#117 114 requested uri dot removal
  inc/RequestParser.hpp
  inc/error.hpp
  src/RequestParser.cpp
  test/integration/server_response/test_invalid.py
  test/unit/test_parseHeader_RequestLine.cpp
Labels: bug
