Repository u413-284-si/webserv, pull requests merged in 2024-09, with the labels that each got.

#47 Update dev container
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .gitignore
  Makefile
Labels: enhancement

#24 9 config parsing check if config file is valid
  .clang-tidy
  Makefile
  config_files/empty_file.conf
  config_files/invalid_listen_value.conf
  config_files/invalid_location_directive.conf
  config_files/invalid_server_directive.conf
  config_files/listen_invalid_ip_high.conf
  config_files/listen_invalid_ip_missing_dot.conf
  config_files/listen_invalid_port_high.conf
  config_files/listen_invalid_port_low.conf
  config_files/listen_ip_and_port.conf
  config_files/listen_only_ip.conf
  config_files/listen_only_port.conf
  config_files/missing_bracket.conf
  config_files/missing_http_block.conf
  config_files/missing_semicolon.conf
  config_files/missing_server_block.conf
  config_files/root_multiple_paths.conf
  config_files/root_no_path.conf
  config_files/several_directives_on_one_line.conf
  config_files/too_many_brackets.conf
  config_files/valid_config.conf
  inc/ConfigFile.hpp
  inc/ConfigFileParser.hpp
  inc/Method.hpp
  inc/ResponseBuilder.hpp
  inc/Server.hpp
  src/ConfigFile.cpp
  src/ConfigFileParser.cpp
  src/LogOstreamInserters.cpp
  src/ResponseBuilder.cpp
  src/Server.cpp
  src/TargetResourceHandler.cpp
  src/main.cpp
  test/test_ConfigFileParser.cpp
  test/test_OstreamInserters.cpp
  test/test_TargetResourceHandler.cpp
  test/test_initVirtualServers.cpp
Labels: enhancement

#44 42 check for completeness of a http request and parse accordingly
  Makefile
  inc/HTTPRequest.hpp
  inc/RequestParser.hpp
  inc/ResponseBuilder.hpp
  inc/Server.hpp
  inc/StatusCode.hpp
  inc/error.hpp
  src/ConfigFileParser.cpp
  src/Connection.cpp
  src/LogOstreamInserters.cpp
  src/RequestParser.cpp
  src/ResponseBuilder.cpp
  src/Server.cpp
  src/utilities.cpp
  test/testBody.cpp
  test/testHeader.cpp
  test/testRequestLine.cpp
  test/test_parseBody.cpp
  test/test_parseHeader_Headers.cpp
  test/test_parseHeader_RequestLine.cpp
Labels: enhancement

#56 Create standard configfile and corresponding target
  Makefile
  config_files/standard_config.conf
  src/ConfigFileParser.cpp
  src/ResponseBuilder.cpp
  src/main.cpp
Labels: bug, enhancement

#50 49 ubsan reference binding to null pointer of type sockaddr
  inc/MockSocketPolicy.hpp
  inc/Server.hpp
  inc/SocketPolicy.hpp
  src/Server.cpp
  src/SocketPolicy.cpp
  test/test_createVirtualServer.cpp
  test/test_initVirtualServers.cpp
Labels: bug

#51 45 remove definition of private copy constructors assignment operators
  inc/Logger.hpp
  src/ALogOutputter.cpp
  src/Directory.cpp
  src/Logger.cpp
Labels: invalid

#63 Fix makefile asan compilation
  .gitignore
  Makefile
Labels: bug

#61 58 handle special cases concerning curly brackets
  config_files/bracket_under_location.conf
  config_files/bracket_under_server.conf
  config_files/directive_close_bracket_same_line.conf
  config_files/directive_close_open_bracket_same_line_under_server.conf
  config_files/directive_open_bracket_same_line.conf
  config_files/invalid_directive_outside_server.conf
  config_files/missing_server_block.conf
  config_files/standard_config.conf
  config_files/whitespaces_between_server_bracket.conf
  inc/ConfigFileParser.hpp
  src/ConfigFileParser.cpp
  test/test_ConfigFileParser.cpp
Labels: bug

#62 59 virtual server selection target resource location
  Makefile
  inc/ConfigFile.hpp
  inc/Connection.hpp
  inc/HTTPRequest.hpp
  inc/HTTPResponse.hpp
  inc/MockSocketPolicy.hpp
  inc/ResponseBodyHandler.hpp
  inc/ResponseBuilder.hpp
  inc/Server.hpp
  inc/SocketPolicy.hpp
  inc/TargetResourceHandler.hpp
  src/AutoindexHandler.cpp
  src/ConfigFile.cpp
  src/Connection.cpp
  src/FileSystemPolicy.cpp
  src/HTTPRequest.cpp
  src/LogOstreamInserters.cpp
  src/ResponseBodyHandler.cpp
  src/ResponseBuilder.cpp
  src/Server.cpp
  src/SocketPolicy.cpp
  src/TargetResourceHandler.cpp
  src/main.cpp
  test/test_ConfigFileParser.cpp
  test/test_OstreamInserters.cpp
  test/test_ResponseBodyHandler.cpp
  test/test_SocketPolicy_retrieveSocketInfo.cpp
  test/test_TargetResourceHandler.cpp
  test/test_acceptConnections.cpp
  test/test_checkForTimeout.cpp
  test/test_connectionReceiveHeader.cpp
  test/test_connectionSendResponse.cpp
  test/test_createVirtualServer.cpp
  test/test_initVirtualServers.cpp
  test/test_registerConnection.cpp
  test/test_selectServerConfig.cpp
  test/test_shutdownServer.cpp
Labels: enhancement

#65 Feat static website
  html/content.html
  html/css/cgi.css
  html/css/styles.css
  html/directory/alien_frogman.png
  html/directory/random.txt
  html/directory/secret.html
  html/favicon.ico
  html/images.html
  html/images/butterfly.jpg
  html/images/cat.jpg
  html/images/chicken.png
  html/images/digi_wolf.webp
  html/images/northern_lights.jpg
  html/images/tree.png
  html/images/work.webp
  html/index.html
  html/run_cgi.html
  html/styled.html
  src/ConfigFile.cpp
  test/test_TargetResourceHandler.cpp
Labels: enhancement

#67 64 responsestream of responsebuilder not cleared of previous response
  inc/Connection.hpp
  inc/ResponseBuilder.hpp
  inc/Server.hpp
  src/Connection.cpp
  src/LogOstreamInserters.cpp
  src/ResponseBuilder.cpp
  src/Server.cpp
  test/test_OstreamInserters.cpp
  test/test_connectionReceiveHeader.cpp
  test/test_connectionSendResponse.cpp
Labels: bug

#76 68 doubled reason phrase
  src/LogOstreamInserters.cpp
  test/test_OstreamInserters.cpp
Labels: bug
