Repository u413-284-si/webserv, pull requests merged in 2025-01, with the labels that each got.

#111 80 implement method delete
  Makefile
  inc/DeleteHandler.hpp
  inc/FileSystemPolicy.hpp
  inc/FileWriteHandler.hpp
  inc/MockFileSystemPolicy.hpp
  inc/ResponseBodyHandler.hpp
  src/ConfigFile.cpp
  src/DeleteHandler.cpp
  src/FileSystemPolicy.cpp
  src/ResponseBodyHandler.cpp
  src/ResponseBuilder.cpp
  src/Server.cpp
  test/testRequests/reqDel
  test/test_DeleteHandler.cpp
Labels: enhancement

#121 119 chunk data cannot contain newline
  inc/RequestParser.hpp
  inc/Server.hpp
  inc/error.hpp
  src/ConfigFile.cpp
  src/RequestParser.cpp
  src/Server.cpp
  test/integration/server_response/test_POST.py
  test/integration/server_response/test_invalid.py
  test/unit/test_isDuplicateServer.cpp
  test/unit/test_parseBody.cpp
  test/unit/test_parseHeader_Headers.cpp
  test/unit/test_parseHeader_RequestLine.cpp
Labels: bug

#129 127 bug in cleanup of closed connections
  inc/Server.hpp
  src/Server.cpp
  test/integration/server_response/test_invalid.py
  test/unit/test_connectionReceiveBody.cpp
  test/unit/test_connectionReceiveHeader.cpp
  test/unit/test_connectionSendResponse.cpp
  test/unit/test_handleCompleteRequestHeader.cpp
  test/unit/test_shutdownServer.cpp
Labels: bug

#134 133 filewritehandler does not set statusforbidden
  inc/FileWriteHandler.hpp
  src/DeleteHandler.cpp
  src/FileWriteHandler.cpp
  src/ResponseBodyHandler.cpp
  test/integration/server_response/test_POST.py
  test/integration/server_response/test_error.py
  test/unit/test_FileWriteHandler.cpp
Labels: bug

#140 126 status 405 response should include allow header
  Makefile
  inc/ResponseBodyHandler.hpp
  src/ResponseBodyHandler.cpp
  src/ResponseBuilder.cpp
  test/integration/server_response/test_error.py
  test/unit/test_ResponseBuilder.cpp
Labels: bug

#146 136 empty serverlocation block should not cause error
  config_files/empty_server.conf
  inc/ConfigFileParser.hpp
  src/ConfigFileParser.cpp
Labels: bug

#149 143 requestparser should act on header connection
  inc/RequestParser.hpp
  inc/error.hpp
  src/RequestParser.cpp
  test/unit/test_parseHeader_Headers.cpp
Labels: bug, enhancement

#128 123 refactor server for testability
  Makefile
  inc/AutoindexHandler.hpp
  inc/DeleteHandler.hpp
  inc/Directory.hpp
  inc/FileSystemOps.hpp
  inc/FileWriteHandler.hpp
  inc/MockFileSystemOps.hpp
  inc/MockProcessOps.hpp
  inc/MockSocketOps.hpp
  inc/ProcessOps.hpp
  inc/RequestParser.hpp
  inc/ResponseBodyHandler.hpp
  inc/ResponseBuilder.hpp
  inc/Server.hpp
  inc/SocketOps.hpp
  inc/TargetResourceHandler.hpp
  inc/test_helpers.hpp
  src/AutoindexHandler.cpp
  src/CGIHandler.cpp
  src/DeleteHandler.cpp
  src/Directory.cpp
  src/FileSystemOps.cpp
  src/FileWriteHandler.cpp
  src/ProcessOps.cpp
  src/RequestParser.cpp
  src/ResponseBodyHandler.cpp
  src/ResponseBuilder.cpp
  src/Server.cpp
  src/SocketOps.cpp
  src/TargetResourceHandler.cpp
  src/main.cpp
  test/unit/test_AutoindexHandler.cpp
  test/unit/test_DeleteHandler.cpp
  test/unit/test_FileWriteHandler.cpp
  test/unit/test_ResponseBodyHandler.cpp
  test/unit/test_ResponseBuilder.cpp
  test/unit/test_SocketOps_retrieveSocketInfo.cpp
  test/unit/test_SocketPolicy_retrieveSocketInfo.cpp
  test/unit/test_TargetResourceHandler.cpp
  test/unit/test_acceptConnections.cpp
  test/unit/test_checkForTimeout.cpp
  test/unit/test_connectionBuildResponse.cpp
  test/unit/test_connectionHandleTimeout.cpp
  test/unit/test_connectionReceiveBody.cpp
  test/unit/test_connectionReceiveFromCGI.cpp
  test/unit/test_connectionReceiveHeader.cpp
  test/unit/test_connectionSendResponse.cpp
  test/unit/test_connectionSendToCGI.cpp
  test/unit/test_createVirtualServer.cpp
  test/unit/test_handleBody.cpp
  test/unit/test_handleCompleteRequestHeader.cpp
  test/unit/test_handleEvent.cpp
  test/unit/test_helpers.cpp
  test/unit/test_initVirtualServers.cpp
  test/unit/test_isDuplicateServer.cpp
  test/unit/test_registerCGIFileDescriptor.cpp
  test/unit/test_registerConnection.cpp
  test/unit/test_registerVirtualServer.cpp
  test/unit/test_shutdownServer.cpp
Labels: enhancement

#125 Feat add more integration tests
  Makefile
  config_files/integration_test_config.conf
  html/recursion/recursion/recursion/recursion/recursion/recursion/recursion/recursion/recursion/recursion/recursion/placeholder
  src/ConfigFile.cpp
  src/ResponseBuilder.cpp
  src/TargetResourceHandler.cpp
  test/integration/conftest.py
  test/integration/server_management/test_signal.py
  test/integration/server_response/conftest.py
  test/integration/server_response/test_CGI.py
  test/integration/server_response/test_GET.py
  test/integration/server_response/test_POST.py
  test/integration/server_response/test_error.py
  test/integration/server_response/test_error3xx.py
  test/integration/server_response/test_error4xx.py
  test/integration/server_response/test_error5xx.py
  test/integration/server_response/test_invalid.py
  test/integration/utils/__init__.py
  test/integration/utils/utils.py
Labels: enhancement

#152 137 location path invalid amount of parameters
  config_files/location_empty_path.conf
  config_files/location_multiple_paths.conf
  inc/ConfigFileParser.hpp
  inc/error.hpp
  src/ConfigFileParser.cpp
  test/unit/test_ConfigFileParser.cpp
Labels: bug

#144 138 update static webiste
  cgi-bin/badBoi.sh
  cgi-bin/create_textfile.py
  cgi-bin/upload.py
  cgi-bin/upperCase.sh
  config_files/integration_test_config.conf
  html/css/styles.css
  html/delete.html
  html/index.html
  html/run_cgi.html
  inc/AutoindexHandler.hpp
  src/AutoindexHandler.cpp
  src/ConfigFile.cpp
  src/ResponseBodyHandler.cpp
  test/integration/server_response/test_CGI.py
  test/unit/test_AutoindexHandler.cpp
Labels: enhancement

#151 145 autoindex is handled instead of post
  inc/ResponseBodyHandler.hpp
  inc/StatusCode.hpp
  src/ResponseBodyHandler.cpp
  src/StatusCode.cpp
  test/unit/test_ResponseBodyHandler.cpp
Labels: bug

#160 155 multiple root directives within one server/location should be invalid
  config_files/location_multiple_roots.conf
  config_files/server_multiple_roots.conf
  inc/ConfigFileParser.hpp
  inc/error.hpp
  src/ConfigFileParser.cpp
  test/unit/test_ConfigFileParser.cpp
Labels: bug

#159 142 setup testing with siege
  .gitignore
  Makefile
  html/css/styles.css
  html/empty.html
  html/images.html
  html/images_external.html
  html/index.html
  src/RequestParser.cpp
  src/Server.cpp
  test/siege/siege.conf
  test/siege/urls.txt
Labels: enhancement

#170 167 adapt status code functions
  inc/StatusCode.hpp
  src/LogOstreamInserters.cpp
  src/StatusCode.cpp
Labels: refactor

#174 173 add valgrind test with automated request delivery
  Makefile
  src/RequestParser.cpp
  test/requester/requester.py
  test/requester/requests.txt
Labels: bug, enhancement

#176 165 trimtrailingwhitespace should return string
  inc/utilities.hpp
  src/ConfigFileParser.cpp
  src/RequestParser.cpp
  src/ResponseBodyHandler.cpp
  src/utilities.cpp
Labels: refactor

#180 179 fix directive inheritance
  inc/ConfigFileParser.hpp
  src/ConfigFileParser.cpp
  test/config_files/directive_inheritance.conf
  test/unit/src/test_ConfigFileParser.cpp
Labels: bug

#177 168 requestparserparseheader should not set status
  inc/RequestParser.hpp
  src/RequestParser.cpp
  src/Server.cpp
  test/unit/src/test_parseHeader_RequestLine.cpp
Labels: enhancement, refactor

#181 178 add integration tests
  cgi-bin/invalid_header_connection.sh
  cgi-bin/invalid_header_status.sh
  cgi-bin/no_cgi_field.sh
  cgi-bin/no_header.sh
  config_files/example.conf
  src/ConfigFile.cpp
  src/DeleteHandler.cpp
  src/ResponseBodyHandler.cpp
  test/integration/server_response/conftest.py
  test/integration/server_response/test_CGI.py
  test/integration/server_response/test_DELETE.py
  test/integration/server_response/test_POST.py
  test/integration/server_response/test_error3xx.py
  test/integration/server_response/test_error4xx.py
  test/integration/server_response/test_error5xx.py
  test/unit/src/test_ResponseBodyHandler.cpp
Labels: bug, enhancement
